title: Old Man Yells at HEMA
description: Things I think that are probably wrong, Art, and why you are also probably wrong.
url: "https://old-man-yells-at-hema.github.io" # e.g., https://oldmanyellsathema.github.io or https://proveitwithiron.com
baseurl: "/YOUR-REPO-NAME" # e.g., /old-man-yells-at-hema for project pages; leave blank for user/organization site
theme: minima
minima:
  skin: dark

author:
  name: Geoffrey Harrington

# Add top‑nav pages (files must exist in repo root)
header_pages:
  - about.md
  - gallery.md
  - posts.html


# Plugins supported by GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Markdown + permalinks
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/

future: true
timezone: America/Los_Angeles

