---

---

title: Old Man Yells at HEMA
description: Things I think that are probably wrong, Art, and why you are also probably wrong.
url: "https://oldmanyellsathema.github.io"   # no trailing slash
baseurl: "/old-man-yells-at-hema"            # leading slash, no trailing slash

author:
  name: Me

# Add top-nav pages (files must exist in repo root)
header_pages:
  - library.md     # Library hub
  - posts.html

# Collections
collections:
  library:
    output: true
    permalink: /library/:section/:title/

defaults:
  - scope:
      path: ""
      type: library
    values:
      layout: library_item

# Plugins supported by GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Markdown + permalinks
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/

future: true
timezone: America/Los_Angeles



