title: Old Man Yells at HEMA
description: Things I think that are probably wrong, Art, and why you are also probably wrong.
url: "https://oldmanyellsathema.github.io"
baseurl: "/old-man-yells-at-hema"

# Top nav — make sure these files actually exist
header_pages:
  - library/index.md
  - posts.html

# Plugins supported by GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Library collection
collections:
  library:
    output: true
    permalink: /library/:title/
  gallery:
    output: true
    permalink: /gallery/:title/
  recipes:
    output: true
    permalink: /recipes/:title/

defaults:
  - scope:
      path: ""
      type: library
    values:
      layout: library_item
  - scope:
      path: ""
      type: gallery
    values:
      layout: gallery_item
  - scope:
      path: ""
      type: recipes
    values:
      layout: recipes_item


# Markdown + permalinks
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/
future: true
timezone: America/Los_Angeles

